services:
  traefik:
    image: traefik:v3.6.2
    
  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    
  kafka:
    image: confluentinc/cp-kafka:7.9.0
    
  postgres:
    image: postgres:17.7-alpine
    
  prometheus:
    image: prom/prometheus:v3.7.3
    
  grafana:
    image: grafana/grafana:12.3.0
    
  loki:
    image: grafana/loki:3.5.8
    
  promtail:
    image: grafana/promtail:3.5.8